export interface KeyboardKey {
  display: string;
  latex: string;
  displayIsLatex?: boolean;
}

export interface KeyboardSection {
  id: string;
  label: string;
  keys: KeyboardKey[];
}

export interface CustomCommand {
  token: string;
  label: string;
}

export const KEYBOARD_SECTIONS: KeyboardSection[] = [
  {
    id: 'operators',
    label: 'Operatori',
    keys: [
      { display: '+', latex: '+' },
      { display: '-', latex: '-' },
      { display: '\\times', latex: '\\times', displayIsLatex: true },
      { display: '\\div', latex: '\\div', displayIsLatex: true },
      { display: '\\cdot', latex: '\\cdot', displayIsLatex: true },
      { display: '/', latex: '/' },
      { display: '\\pm', latex: '\\pm', displayIsLatex: true },
      { display: '=', latex: '=' },
      { display: '\\neq', latex: '\\neq', displayIsLatex: true },
      { display: '<', latex: '<' },
      { display: '>', latex: '>' },
      { display: '\\leq', latex: '\\leq', displayIsLatex: true },
      { display: '\\geq', latex: '\\geq', displayIsLatex: true },
    ],
  },
  {
    id: 'templates',
    label: 'Template',
    keys: [
      { display: '\\frac{a}{b}', latex: '\\frac{}{}', displayIsLatex: true },
      { display: '\\sqrt{x}', latex: '\\sqrt{}', displayIsLatex: true },
      { display: '\\sqrt[n]{x}', latex: '\\sqrt[]{}', displayIsLatex: true },
      { display: 'x^{n}', latex: '^{}', displayIsLatex: true },
      { display: 'x_{n}', latex: '_{}', displayIsLatex: true },
      { display: 'x^{-1}', latex: '^{-1}', displayIsLatex: true },
      { display: '\\overline{x}', latex: '\\overline{}', displayIsLatex: true },
      { display: '\\underline{x}', latex: '\\underline{}', displayIsLatex: true },
      { display: '(\\,)', latex: '\\left(\\right)' },
      { display: '[\\,]', latex: '\\left[\\right]' },
      { display: '[', latex: '[' },
      { display: ']', latex: ']' },
      { display: '|', latex: '|' },
      { display: '|\\square|', latex: '\\left|\\right|', displayIsLatex: true },
      { display: '\\|\\square\\|', latex: '\\left\\|\\right\\|', displayIsLatex: true },
      { display: 'x^{\\complement}', latex: '^{\\complement}', displayIsLatex: true },
      { display: "x'", latex: '\\prime', displayIsLatex: true },
      { display: "x''", latex: '\\prime\\prime', displayIsLatex: true },
    ],
  },
  {
    id: 'functions',
    label: 'Funzioni',
    keys: [
      { display: '\\sin', latex: '\\sin', displayIsLatex: true },
      { display: '\\cos', latex: '\\cos', displayIsLatex: true },
      { display: '\\tan', latex: '\\tan', displayIsLatex: true },
      { display: '\\sin^{-1}', latex: '\\sin^{-1}', displayIsLatex: true },
      { display: '\\cos^{-1}', latex: '\\cos^{-1}', displayIsLatex: true },
      { display: '\\tan^{-1}', latex: '\\tan^{-1}', displayIsLatex: true },
      { display: '\\ln', latex: '\\ln', displayIsLatex: true },
      { display: '\\log', latex: '\\log', displayIsLatex: true },
      { display: '\\log_{10}', latex: '\\log_{10}', displayIsLatex: true },
      { display: '\\exp', latex: '\\exp', displayIsLatex: true },
      { display: 'abs', latex: '\\operatorname{abs}' },
      { display: '\\lim', latex: '\\lim', displayIsLatex: true },
      { display: '\\sum', latex: '\\sum', displayIsLatex: true },
      { display: '\\prod', latex: '\\prod', displayIsLatex: true },
      { display: '\\int', latex: '\\int', displayIsLatex: true },
      { display: '\\iint', latex: '\\iint', displayIsLatex: true },
    ],
  },
  {
    id: 'logic-sets',
    label: 'Logica & Insiemi',
    keys: [
      { display: '\\forall', latex: '\\forall', displayIsLatex: true },
      { display: '\\exists', latex: '\\exists', displayIsLatex: true },
      { display: '\\nexists', latex: '\\nexists', displayIsLatex: true },
      { display: '\\neg', latex: '\\neg', displayIsLatex: true },
      { display: '\\in', latex: '\\in', displayIsLatex: true },
      { display: '\\notin', latex: '\\notin', displayIsLatex: true },
      { display: '\\ni', latex: '\\ni', displayIsLatex: true },
      { display: '\\not\\ni', latex: '\\not\\ni', displayIsLatex: true },
      { display: '\\subset', latex: '\\subset', displayIsLatex: true },
      { display: '\\subseteq', latex: '\\subseteq', displayIsLatex: true },
      { display: '\\cup', latex: '\\cup', displayIsLatex: true },
      { display: '\\cap', latex: '\\cap', displayIsLatex: true },
      { display: '\\to', latex: '\\to', displayIsLatex: true },
      { display: '\\Rightarrow', latex: '\\Rightarrow', displayIsLatex: true },
      { display: '\\leftarrow', latex: '\\leftarrow', displayIsLatex: true },
      { display: '\\Leftarrow', latex: '\\Leftarrow', displayIsLatex: true },
      { display: '\\leftrightarrow', latex: '\\leftrightarrow', displayIsLatex: true },
      { display: '\\Leftrightarrow', latex: '\\Leftrightarrow', displayIsLatex: true },
      { display: '\\mid', latex: '\\mid', displayIsLatex: true },
    ],
  },
  {
    id: 'constants',
    label: 'Costanti & Altro',
    keys: [
      { display: 'e', latex: 'e' },
      { display: 'i', latex: 'i' },
      { display: '\\pi', latex: '\\pi', displayIsLatex: true },
      { display: '\\tau', latex: '\\tau', displayIsLatex: true },
      { display: 'd', latex: 'd' },
      { display: '\\partial', latex: '\\partial', displayIsLatex: true },
      { display: '\\infty', latex: '\\infty', displayIsLatex: true },
      { display: '!', latex: '!' },
      { display: ',', latex: ',' },
      { display: ';', latex: ';' },
      { display: ':', latex: ':' },
      { display: '\\ast', latex: '\\ast', displayIsLatex: true },
    ],
  },
  {
    id: 'greek-lower',
    label: 'Greco minuscolo',
    keys: [
      { display: '\\alpha', latex: '\\alpha', displayIsLatex: true },
      { display: '\\beta', latex: '\\beta', displayIsLatex: true },
      { display: '\\gamma', latex: '\\gamma', displayIsLatex: true },
      { display: '\\delta', latex: '\\delta', displayIsLatex: true },
      { display: '\\epsilon', latex: '\\epsilon', displayIsLatex: true },
      { display: '\\zeta', latex: '\\zeta', displayIsLatex: true },
      { display: '\\eta', latex: '\\eta', displayIsLatex: true },
      { display: '\\theta', latex: '\\theta', displayIsLatex: true },
      { display: '\\iota', latex: '\\iota', displayIsLatex: true },
      { display: '\\kappa', latex: '\\kappa', displayIsLatex: true },
      { display: '\\lambda', latex: '\\lambda', displayIsLatex: true },
      { display: '\\mu', latex: '\\mu', displayIsLatex: true },
      { display: '\\nu', latex: '\\nu', displayIsLatex: true },
      { display: '\\xi', latex: '\\xi', displayIsLatex: true },
      { display: 'o', latex: 'o' },
      { display: '\\rho', latex: '\\rho', displayIsLatex: true },
      { display: '\\sigma', latex: '\\sigma', displayIsLatex: true },
      { display: '\\upsilon', latex: '\\upsilon', displayIsLatex: true },
      { display: '\\varphi', latex: '\\varphi', displayIsLatex: true },
      { display: '\\chi', latex: '\\chi', displayIsLatex: true },
      { display: '\\psi', latex: '\\psi', displayIsLatex: true },
      { display: '\\omega', latex: '\\omega', displayIsLatex: true },
      // Variants
      { display: '\\varepsilon', latex: '\\varepsilon', displayIsLatex: true },
      { display: '\\vartheta', latex: '\\vartheta', displayIsLatex: true },
      { display: '\\varkappa', latex: '\\varkappa', displayIsLatex: true },
      { display: '\\varpi', latex: '\\varpi', displayIsLatex: true },
      { display: '\\varrho', latex: '\\varrho', displayIsLatex: true },
      { display: '\\varsigma', latex: '\\varsigma', displayIsLatex: true },
      { display: '\\phi', latex: '\\phi', displayIsLatex: true },
    ],
  },
  {
    id: 'greek-upper',
    label: 'Greco maiuscolo',
    keys: [
      { display: '\\Alpha', latex: '\\Alpha', displayIsLatex: true },
      { display: '\\Beta', latex: '\\Beta', displayIsLatex: true },
      { display: '\\Gamma', latex: '\\Gamma', displayIsLatex: true },
      { display: '\\Delta', latex: '\\Delta', displayIsLatex: true },
      { display: '\\Epsilon', latex: '\\Epsilon', displayIsLatex: true },
      { display: '\\Zeta', latex: '\\Zeta', displayIsLatex: true },
      { display: '\\Eta', latex: '\\Eta', displayIsLatex: true },
      { display: '\\Theta', latex: '\\Theta', displayIsLatex: true },
      { display: '\\Iota', latex: '\\Iota', displayIsLatex: true },
      { display: '\\Kappa', latex: '\\Kappa', displayIsLatex: true },
      { display: '\\Lambda', latex: '\\Lambda', displayIsLatex: true },
      { display: '\\Mu', latex: '\\Mu', displayIsLatex: true },
      { display: '\\Nu', latex: '\\Nu', displayIsLatex: true },
      { display: '\\Xi', latex: '\\Xi', displayIsLatex: true },
      { display: '\\Omicron', latex: '\\Omicron', displayIsLatex: true },
      { display: '\\Pi', latex: '\\Pi', displayIsLatex: true },
      { display: '\\Sigma', latex: '\\Sigma', displayIsLatex: true },
      { display: '\\Tau', latex: '\\Tau', displayIsLatex: true },
      { display: '\\Upsilon', latex: '\\Upsilon', displayIsLatex: true },
      { display: '\\Phi', latex: '\\Phi', displayIsLatex: true },
      { display: '\\Chi', latex: '\\Chi', displayIsLatex: true },
      { display: '\\Psi', latex: '\\Psi', displayIsLatex: true },
      { display: '\\Omega', latex: '\\Omega', displayIsLatex: true },
    ],
  },
];

export const CUSTOM_COMMANDS: CustomCommand[] = [
  { token: '&&completamento&&', label: 'Completamento' },
  { token: '<nome>', label: 'Nome simulazione' },
  { token: '<linkcorrezione>', label: 'Link correzione' },
  { token: '<linksimulazioni>', label: 'Link simulazioni' },
  { token: '<punteggio>', label: 'Punteggio' },
  { token: '<massimo>', label: 'Max punteggio' },
  { token: '<tempo>', label: 'Tempo' },
];
