/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestsRouteImport } from './routes/_authenticated/tests'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAttributesRouteImport } from './routes/_authenticated/attributes'
import { Route as AuthenticatedQuestionsIndexRouteImport } from './routes/_authenticated/questions/index'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated/pools/index'
import { Route as AuthenticatedMySlotsIndexRouteImport } from './routes/_authenticated/my-slots/index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedQuestionsToReviewRouteImport } from './routes/_authenticated/questions/to-review'
import { Route as AuthenticatedQuestionsImportRouteImport } from './routes/_authenticated/questions/import'
import { Route as AuthenticatedQuestionsCreateRouteImport } from './routes/_authenticated/questions/create'
import { Route as AuthenticatedQuestionsQuestionIdRouteImport } from './routes/_authenticated/questions/$questionId'
import { Route as AuthenticatedPoolsPoolIdRouteImport } from './routes/_authenticated/pools/$poolId'
import { Route as AuthenticatedCollectionsCreateRouteImport } from './routes/_authenticated/collections/create'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns/$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestsRoute = AuthenticatedTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttributesRoute = AuthenticatedAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionsIndexRoute =
  AuthenticatedQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMySlotsIndexRoute =
  AuthenticatedMySlotsIndexRouteImport.update({
    id: '/my-slots/',
    path: '/my-slots/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsToReviewRoute =
  AuthenticatedQuestionsToReviewRouteImport.update({
    id: '/questions/to-review',
    path: '/questions/to-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsImportRoute =
  AuthenticatedQuestionsImportRouteImport.update({
    id: '/questions/import',
    path: '/questions/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsCreateRoute =
  AuthenticatedQuestionsCreateRouteImport.update({
    id: '/questions/create',
    path: '/questions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionsQuestionIdRoute =
  AuthenticatedQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoolsPoolIdRoute =
  AuthenticatedPoolsPoolIdRouteImport.update({
    id: '/pools/$poolId',
    path: '/pools/$poolId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCreateRoute =
  AuthenticatedCollectionsCreateRouteImport.update({
    id: '/collections/create',
    path: '/collections/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/attributes': typeof AuthenticatedAttributesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/collections/create': typeof AuthenticatedCollectionsCreateRoute
  '/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/questions/$questionId': typeof AuthenticatedQuestionsQuestionIdRoute
  '/questions/create': typeof AuthenticatedQuestionsCreateRoute
  '/questions/import': typeof AuthenticatedQuestionsImportRoute
  '/questions/to-review': typeof AuthenticatedQuestionsToReviewRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/my-slots/': typeof AuthenticatedMySlotsIndexRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/questions/': typeof AuthenticatedQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/attributes': typeof AuthenticatedAttributesRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/collections/create': typeof AuthenticatedCollectionsCreateRoute
  '/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/questions/$questionId': typeof AuthenticatedQuestionsQuestionIdRoute
  '/questions/create': typeof AuthenticatedQuestionsCreateRoute
  '/questions/import': typeof AuthenticatedQuestionsImportRoute
  '/questions/to-review': typeof AuthenticatedQuestionsToReviewRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/my-slots': typeof AuthenticatedMySlotsIndexRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_authenticated/attributes': typeof AuthenticatedAttributesRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/tests': typeof AuthenticatedTestsRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/_authenticated/collections/create': typeof AuthenticatedCollectionsCreateRoute
  '/_authenticated/pools/$poolId': typeof AuthenticatedPoolsPoolIdRoute
  '/_authenticated/questions/$questionId': typeof AuthenticatedQuestionsQuestionIdRoute
  '/_authenticated/questions/create': typeof AuthenticatedQuestionsCreateRoute
  '/_authenticated/questions/import': typeof AuthenticatedQuestionsImportRoute
  '/_authenticated/questions/to-review': typeof AuthenticatedQuestionsToReviewRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/my-slots/': typeof AuthenticatedMySlotsIndexRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/questions/': typeof AuthenticatedQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/attributes'
    | '/clients'
    | '/dashboard'
    | '/packages'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/subjects'
    | '/tests'
    | '/campaigns/$campaignId'
    | '/collections/create'
    | '/pools/$poolId'
    | '/questions/$questionId'
    | '/questions/create'
    | '/questions/import'
    | '/questions/to-review'
    | '/campaigns/'
    | '/collections/'
    | '/my-slots/'
    | '/pools/'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/attributes'
    | '/clients'
    | '/dashboard'
    | '/packages'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/subjects'
    | '/tests'
    | '/campaigns/$campaignId'
    | '/collections/create'
    | '/pools/$poolId'
    | '/questions/$questionId'
    | '/questions/create'
    | '/questions/import'
    | '/questions/to-review'
    | '/campaigns'
    | '/collections'
    | '/my-slots'
    | '/pools'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/_authenticated/attributes'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/packages'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/subjects'
    | '/_authenticated/tests'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/collections/create'
    | '/_authenticated/pools/$poolId'
    | '/_authenticated/questions/$questionId'
    | '/_authenticated/questions/create'
    | '/_authenticated/questions/import'
    | '/_authenticated/questions/to-review'
    | '/_authenticated/campaigns/'
    | '/_authenticated/collections/'
    | '/_authenticated/my-slots/'
    | '/_authenticated/pools/'
    | '/_authenticated/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests': {
      id: '/_authenticated/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attributes': {
      id: '/_authenticated/attributes'
      path: '/attributes'
      fullPath: '/attributes'
      preLoaderRoute: typeof AuthenticatedAttributesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/': {
      id: '/_authenticated/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-slots/': {
      id: '/_authenticated/my-slots/'
      path: '/my-slots'
      fullPath: '/my-slots/'
      preLoaderRoute: typeof AuthenticatedMySlotsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/to-review': {
      id: '/_authenticated/questions/to-review'
      path: '/questions/to-review'
      fullPath: '/questions/to-review'
      preLoaderRoute: typeof AuthenticatedQuestionsToReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/import': {
      id: '/_authenticated/questions/import'
      path: '/questions/import'
      fullPath: '/questions/import'
      preLoaderRoute: typeof AuthenticatedQuestionsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/create': {
      id: '/_authenticated/questions/create'
      path: '/questions/create'
      fullPath: '/questions/create'
      preLoaderRoute: typeof AuthenticatedQuestionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/questions/$questionId': {
      id: '/_authenticated/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/$poolId': {
      id: '/_authenticated/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof AuthenticatedPoolsPoolIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/create': {
      id: '/_authenticated/collections/create'
      path: '/collections/create'
      fullPath: '/collections/create'
      preLoaderRoute: typeof AuthenticatedCollectionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAttributesRoute: typeof AuthenticatedAttributesRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedTestsRoute: typeof AuthenticatedTestsRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRoute
  AuthenticatedCollectionsCreateRoute: typeof AuthenticatedCollectionsCreateRoute
  AuthenticatedPoolsPoolIdRoute: typeof AuthenticatedPoolsPoolIdRoute
  AuthenticatedQuestionsQuestionIdRoute: typeof AuthenticatedQuestionsQuestionIdRoute
  AuthenticatedQuestionsCreateRoute: typeof AuthenticatedQuestionsCreateRoute
  AuthenticatedQuestionsImportRoute: typeof AuthenticatedQuestionsImportRoute
  AuthenticatedQuestionsToReviewRoute: typeof AuthenticatedQuestionsToReviewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedMySlotsIndexRoute: typeof AuthenticatedMySlotsIndexRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
  AuthenticatedQuestionsIndexRoute: typeof AuthenticatedQuestionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttributesRoute: AuthenticatedAttributesRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedTestsRoute: AuthenticatedTestsRoute,
  AuthenticatedCampaignsCampaignIdRoute: AuthenticatedCampaignsCampaignIdRoute,
  AuthenticatedCollectionsCreateRoute: AuthenticatedCollectionsCreateRoute,
  AuthenticatedPoolsPoolIdRoute: AuthenticatedPoolsPoolIdRoute,
  AuthenticatedQuestionsQuestionIdRoute: AuthenticatedQuestionsQuestionIdRoute,
  AuthenticatedQuestionsCreateRoute: AuthenticatedQuestionsCreateRoute,
  AuthenticatedQuestionsImportRoute: AuthenticatedQuestionsImportRoute,
  AuthenticatedQuestionsToReviewRoute: AuthenticatedQuestionsToReviewRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedMySlotsIndexRoute: AuthenticatedMySlotsIndexRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
  AuthenticatedQuestionsIndexRoute: AuthenticatedQuestionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
